### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lukakostic** [keijiro/TrailBoids#1]
Why are you doing this in update:

            foreach (var boid in _boids) SteerBoid(boid);
            foreach (var boid in _boids) AdvanceBoid(boid);

and not just putting it in one foreach?

And why not make a boid script and have each object do its own steering and advancing in update?

Im reading up on data oriented design (and unity ecs) and this seems to be similar to principles there so im wondering if its related

**Comment by keijiro** [comment]
I have to admit that this is just a quick and dirty project. There is no proper reason for them -- just because that's easy to write. I wouldn't recommend trying to learn something from them.
